language: python
python: 2.7
sudo: false
env:
  matrix:
    - PLONE_VERSION=5.0.x
    - PLONE_VERSION=5.1.x
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install -r requirements.txt
install:
  - cp test-$PLONE_VERSION.cfg buildout.cfg
  - buildout annotate
  - buildout -t 10
script:
  - bin/code-analysis
  - bin/test
after_success:
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
